/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.seti2.components;

import com.rameses.rcp.common.Column;

/**
 *
 * @author dell
 */
public class ItemPanel extends javax.swing.JPanel {

    private String cols;
    private String orderBy;
    
    /**
     * Creates new form ItemPanel
     */
    public ItemPanel() {
        initComponents();
    }

    public String getHandler() {
        return dataTable.getHandler();
    }
    
    public Column[] getColumns() {
        return dataTable.getColumns();
    }
    
    /***
     * fix the handler to match the ff. expression
     * itemHandlers.<name_of_complex_field>
     */ 
    public void setHandler(String s) {
        if( s.startsWith("entity")) {
            s = s.substring( s.indexOf(".") );
        }
        s = "itemHandlers."+s;
        dataTable.setHandler(s);
        dataTable.setId(s);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataTable = new com.rameses.rcp.control.XDataTable();

        setLayout(new java.awt.BorderLayout());

        dataTable.setHandler("listHandler");
        add(dataTable, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XDataTable dataTable;
    // End of variables declaration//GEN-END:variables

    public String getCols() {
        return cols;
    }

    public void setCols(String cols) {
        this.cols = cols;
    }

    public String getOrderBy() {
        return orderBy;
    }

    public void setOrderBy(String orderBy) {
        this.orderBy = orderBy;
    }

    
    
}
