/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.seti2.components;

import com.rameses.rcp.common.Column;

/**
 *
 * @author dell
 */
public class ListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListPanel
     */
    public ListPanel() {
        initComponents();
        setHandler("listHandler"); 
        tblList.setIndex(-1);
    }

    public String getHandler() {
        return tblList.getHandler();
    }
    
    public boolean isDynamic() {
        return tblList.isDynamic();
    }
    
    public void setDynamic( boolean b ) {
        tblList.setDynamic(b);
    }

    public Column[] getColumns() {
        return tblList.getColumns();
    }
    
    public void setColumns(Column[] cols ) {
        tblList.setColumns(cols);
    }
    
    public void setHandler(String s) {
        tblList.setHandler(s);
        tblList.setId(s);
        btnMoveFirst.setName(s+".moveFirstPage");
        btnMovePrev.setName(s+".moveBackPage");
        btnMoveNext.setName(s+".moveNextPage");
        btnMoveLast.setName(s+".moveLastPage");
        
        lblRecordCount.setExpression("#{"+ s +".recordCountInfo}");
        lblPageCount.setExpression("#{"+ s +".pageCountInfo}");
    }
    
    public String[] getDepends() {
        return tblList.getDepends();
    }
    
    public void setDepends(String[] arr) {
        tblList.setDepends( arr );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblList = new com.rameses.rcp.control.XDataTable();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        btnMoveFirst = new com.rameses.rcp.control.XButton();
        btnMovePrev = new com.rameses.rcp.control.XButton();
        btnMoveNext = new com.rameses.rcp.control.XButton();
        btnMoveLast = new com.rameses.rcp.control.XButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(35, 0), new java.awt.Dimension(35, 0), new java.awt.Dimension(35, 32767));
        lblRecordCount = new com.rameses.rcp.control.XLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        lblPageCount = new com.rameses.rcp.control.XLabel();

        setLayout(new java.awt.BorderLayout());

        tblList.setHandler("listHandler");
        tblList.setName("selectedItem"); // NOI18N
        tblList.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        add(tblList, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 2, 0));
        com.rameses.rcp.control.layout.XLayout xLayout1 = new com.rameses.rcp.control.layout.XLayout();
        xLayout1.setSpacing(1);
        jPanel1.setLayout(xLayout1);

        jToolBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        btnMoveFirst.setName("listHandler.moveFirstPage"); // NOI18N
        btnMoveFirst.setAutoRefresh(false);
        btnMoveFirst.setFocusable(false);
        btnMoveFirst.setIconResource("images/navbar/first.png");
        jToolBar2.add(btnMoveFirst);

        btnMovePrev.setName("listHandler.moveBackPage"); // NOI18N
        btnMovePrev.setAutoRefresh(false);
        btnMovePrev.setFocusable(false);
        btnMovePrev.setIconResource("images/navbar/previous.png");
        jToolBar2.add(btnMovePrev);

        btnMoveNext.setName("listHandler.moveNextPage"); // NOI18N
        btnMoveNext.setAutoRefresh(false);
        btnMoveNext.setFocusable(false);
        btnMoveNext.setIconResource("images/navbar/next.png");
        btnMoveNext.setImmediate(true);
        jToolBar2.add(btnMoveNext);

        btnMoveLast.setName("listHandler.moveLastPage"); // NOI18N
        btnMoveLast.setAutoRefresh(false);
        btnMoveLast.setFocusable(false);
        btnMoveLast.setIconResource("images/navbar/last.png");
        jToolBar2.add(btnMoveLast);
        jToolBar2.add(filler1);

        jPanel1.add(jToolBar2);

        lblRecordCount.setDepends(new String[] {"selectedItem"});
        lblRecordCount.setExpression("#{recordCountInfo}");
        lblRecordCount.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lblRecordCount.setUseHtml(true);
        jPanel1.add(lblRecordCount);
        jPanel1.add(filler2);

        lblPageCount.setDepends(new String[] {"selectedItem"});
        lblPageCount.setExpression("#{pageCountInfo}");
        lblPageCount.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        lblPageCount.setUseHtml(true);
        jPanel1.add(lblPageCount);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton btnMoveFirst;
    private com.rameses.rcp.control.XButton btnMoveLast;
    private com.rameses.rcp.control.XButton btnMoveNext;
    private com.rameses.rcp.control.XButton btnMovePrev;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar2;
    private com.rameses.rcp.control.XLabel lblPageCount;
    private com.rameses.rcp.control.XLabel lblRecordCount;
    private com.rameses.rcp.control.XDataTable tblList;
    // End of variables declaration//GEN-END:variables
}
