/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.osiris2.themes;

import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.NodeListTemplate;

/**
 *
 * @author dell
 */
@Template(value=NodeListTemplate.class, target="sidebar")
public class NodeListPage extends javax.swing.JPanel {

    /**
     * Creates new form NodeListPage
     */
    public NodeListPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        xList1 = new com.rameses.rcp.control.XList();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        xList1.setExpression("#{item.title}");
        xList1.setHandler("nodeListHandler");
        xList1.setName("selectedNode"); // NOI18N
        xList1.setFixedCellHeight(18);
        jScrollPane1.setViewportView(xList1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XList xList1;
    // End of variables declaration//GEN-END:variables
}
