/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.osiris2.themes;

import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudNodeListPage;

/**
 *
 * @author rameses
 */
@Template(value=CrudNodeListPage.class, target="sidebar")
public class TreeListPage extends javax.swing.JPanel {

    /**
     * Creates new form TreeListPage
     */
    public TreeListPage() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        xTree1 = new com.rameses.rcp.control.XTree();

        setLayout(new java.awt.BorderLayout());

        xTree1.setHandler("treeNode");
        jScrollPane1.setViewportView(xTree1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XTree xTree1;
    // End of variables declaration//GEN-END:variables
}
