/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.seti2.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.common.PageListModel;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author rameses
 */
@Template(FormPage.class)
public class FormListPage extends javax.swing.JPanel {

    /**
     * Creates new form FormListPage
     */
    public FormListPage() {
        initComponents();
        PageListModel m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listPanel1 = new com.rameses.seti2.components.ListPanel();

        setLayout(new java.awt.BorderLayout());
        add(listPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.seti2.components.ListPanel listPanel1;
    // End of variables declaration//GEN-END:variables
}
