/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.rameses.seti2.views;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author Elmo Nazareno
 */
@Template(OKCancelPage.class)
public class DecimalPrompt extends javax.swing.JPanel {

    /**
     * Creates new form DecimalPrompt
     */
    public DecimalPrompt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        jPanel1 = new javax.swing.JPanel();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        setPreferredSize(new java.awt.Dimension(328, 127));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        xLabel1.setExpression("#{title}");
        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        jPanel2.add(xLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 20, 0));
        jPanel1.setLayout(new com.rameses.rcp.control.layout.CenterLayout());

        xDecimalField1.setName("value"); // NOI18N
        xDecimalField1.setPreferredSize(new java.awt.Dimension(140, 22));
        jPanel1.add(xDecimalField1);

        jPanel2.add(jPanel1, java.awt.BorderLayout.SOUTH);

        add(jPanel2, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XLabel xLabel1;
    // End of variables declaration//GEN-END:variables
}
